services:
  app:
    image: ghcr.io/basketikun/infinite-canvas:latest
    container_name: infinite-canvas
    ports:
      - "30026:30026"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
